### ISSUE TITLE
Flashloan Improvements

### ISSUE THREAD

**Issue by jkbpvsc** [mrgnlabs/marginfi-v2#196]
- Defer deposit/borrow limit checks to the end_flashloan ix
- Allow flashloans that improve account health -- allow flashloan if account is in bad health, but health health improves: health at end_flashloan > health at start_flashloan

**Comment by cxp-13** [comment]
where the code location with deposit/borrow limit checks. I don't find it on programs/marginfi/src/instructions/marginfi_account/borrow.rs lending_account_borrow function

**Comment by cxp-13** [comment]
Has this function been completed? I looked at the code and found that when borrowing, health monitoring is skipped.

**Comment by cxp-13** [comment]
`Allow flashloans that improve account health -- allow flashloan if account is in bad health, but health health improves: health at end_flashloan > health at start_flashloan` 
I think this improvement has already been implemented in the code, because according to unit testing, repayment after borrowing meets this description.

**Comment by jgur-psyops** [comment]
completed
